services:
    php:
        image: live-flow-php
        build:
            context: .
            target: php
        container_name: live-flow-php
        volumes:
            - ../..:/live-flow
        ports:
            - 8096:8000
    mysql:
        image: mysql:8.1
        container_name: live-flow-mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=live-flow
            - MYSQL_USER=live-flow
            - MYSQL_PASSWORD=flive-low